name: Generate M3U

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install playwright lxml beautifulsoup4  # 添加beautifulsoup4
        playwright install chromium

    - name: Run script
      working-directory: ./scripts
      run: python generate_m3u.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: m3u-files
        path: scripts/output/
